---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-cnpg-secret
  namespace: threads-dev
spec:
  encryptedData:
    password: AgBNNhB27vsjMG5GeCRIA5jAHkYdzJNu6o9Ctp3cuHnF7ihp/aZCQPdK65G4nI/4dTrn9a44DuXn7whi9remv2zvohx/0dO/PYyBOKT8d4oVYRkJHd/huiJW1WLXBu28qZlPyvrL50l3o9D6yfhDpqMkH38Zdi5rV4JNsjLk2yKEVJD3umOJwgerrb2MMoDaxjtgRIrvqyW5S7bo1m7hWokMT2Jj9Ef9re0N66KnAPV8gVHnzvUSZ8HfMiuAp33Gks+SVmIRgmsG1mrT032xXJcTM9omhhgczr+IxBqv5d5xysnCgT2l2fkNMp8mlVn2xydKbR/jQqY2gTN/q7uayekMLA2OmywJ0oN8XKVn7ziokOtGGzuYg3AwRDxigmOFMqaKzC1iXdAD2RNGeibkxEFbeKF+f+ds19e32aEzJArwbavdTD4NbEfO3WHMb6Q7YrkJEqI+e7EaouECFhtafE6CE0hn78CjPWoS1ZnFWS79RuCCEjSDSQa6d6C93cud36zUEP3bgbPt7Oq+Rp94dwFbyVYXsfmIySAGS8YkO6QRSTCaYA9C/xEbn5fv047QTTDtuMxmZHNxXhtfedMPhEy3bLTqPY//vaVQhy9ckf1sDOYUUtUsUgysrGjESHQaRPMy6f428hCprhd8zzeudEz2D1iPzaS9JdCtFIVFF3sewhglQgtdXrUesUzBFopv3lNBQzNndGMxlEAOlm2p
    username: AgBaxyFHbKUqI5khMh78HTdnsajvXUWtt5KekaNkbo6UjHYYw15SjZ8TIOYHMpaAT28j9b6Ek/ijU0PE2u3YNmOsbQfZm0JQPt6yFvgNXl177+G8bvPGOmEHW6/sPABcqRV4SUWF4BG7aEi6qoIzPjS8LEq20o7QFpu/4zInB6scyhbZjIQNMBenq42mW4ux/ITdHznynDT0aelE2nG2oiBltStQW+bezaRtci/w1SZm2lbb4UwwUbl3AaWRx9lL6p9aqVAPYGJ8tC8BQYAH7DrO5CVCZ48GeSQcuGm1er0Kd2B5k+pNqmZiFx/JfpeW/dkxp/CxVbVt3FIEdcG4jonCe912A3vO583o80/vdtrAw+qOVQHU9wn1BxiVEaRiUnhQrQbVhtOmICO9RlMZM7NpK+1IDbQd0bC9njNIZcvmEM94Ca5o7zp/KJG4hNksBRG7eK4iMW0gvXZen3lQYicucz8oy9K1zgu1/mFibxrwMNEiOpcaf32+mSfbuDHuqQdFwhNSwJDw16yI1Gp/vI89jHQVs7/iFXQlyDHr7wIH082qqOVhLsQ358s2rxPd6AOeYl02Gp/tAvy/Angqnn4SdEoZdnixHjEQDXjC2Sfa8LlevtBw9DcSQevmILctgUqXDgWk1haQYGIDJls2jOaYEB+B4gCjr7tgjjnoPQWJ/JKepFed+TIUwlVyMWtEo2rZIewbgQ==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-cnpg-secret
      namespace: threads-dev
    type: kubernetes.io/basic-auth
