# Secret for CNPG - contains superuser credentials
# CNPG expects specific keys: username, password
apiVersion: v1
kind: Secret
metadata:
  name: postgres-cnpg-secret
type: kubernetes.io/basic-auth
stringData:
  username: namth
  password: "01664157092aA"
