---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-backup-minio-creds
  namespace: threads-dev
spec:
  encryptedData:
    ACCESS_KEY_ID: AgB0ARzElxBtEaRHMJTybUDGFNJ7w9HxuIEI8RqwopyXbzE/rrKb3H89P7wtUq83aFKi8jj3M8FRJOZJfxh5aWeeFL3Zhnrez+ubNOFlhnIbGocnWLclXaRaVv4vlZPQGoB1zhc5I4qzUMzsOVtwuMCtuBeaDJVnkvYNugtebJYOvz88qW5ZbTEgsicAnsRk0yn4RfY1W1SZUCtXyfUONvHX9o60NT3vUbm0darYatdx7stJfoXsHTyvN8M7dGLLJ3P6BVmKRNJSVSDlSQQRKHJYsTSXRm8r/sOR15pSSPUF+1ZZbJdN5bGLElfM/AkkuybVlZk3ad37IjJzMQ75dVBtg7i3R5H1z0NClXpLdz9KYojwPJv7usDS6nVqclMf9FrU4JGxAf+FaYhxL+DEYMd39wER6KG74b2hDQM8eI65/A8l7ZEYFZXjlTnRzKkUstZQDsvVvAllwjzgGgZA2x0697UqQOkGKePg5aYMOKh/C+tzd0+wmszn1iHQEvUDpXDgUqWhzVkvIUMu0tPumwq8zTVmbQ0YLAn6tlGZNgrBGuH9vmKm1YOoQDcmj8P9tSjVDQ0IVlbQidk/IoBHHL4O7Nu5AsaJ00Qanej/GVWOvsfUicKqhVR4ToK0Y14ceUCUWzCx6hR+y3guUDeE4/VjuOkgR9nTHOqbTkGnunwiHJLLfTzHHiAZWjnSOaCHxZpbGq+Hwg==
    ACCESS_SECRET_KEY: AgA/7J/h2baCLyXVIwis5Z2tGVqPAaiXI0t2k3TFdd4pUyseVNVGhqp1pFwinVA9LfTYgis72mHQRde/NVmFm7XbS5IEi/f0ucmsHSsNfGOeP2fTsS5+J3Qt8Mac61lNnufUdNbBTTp37VjsKe8jX0n1FzSTNtmo5+EX0J0hMlNQ9NqmhzRxDSDL8cq61Uk+t1dWeTGCoDap9gCDAZ5HcgoBCjDsvf3+VlrEkEcUxgjePERRdE8FCxEcJs3oZISfGgGS9+PToUSfqHriSmXBeWR9lqSHpvNvPtXhkvxpfNOuwx9MrbE0dPOzQfXUfKrt6iCiE23Ig2u6zcuhPqzNSxc44+xsltXna+zNHH32udekrUesrt27f2qdYh2pEfIMnP3GWfOJUWLard+WVbfvh6jKhRPixYsMoPy9hHtQvCngg31d29twxldf+tLRp0cScjtc+/6i/MfiuphqVbs1Fh95h8ZH/QPYsIdfE5z4iogjgNzrnKFlRCocdrST5rzZGAPDCUeVWYb6nC2W4sKTp9H5QrQSB2jpr7RGxNvX9EOUBrKBd1DLnX/TkGtm3cT6atPIszc5LHc/RYqvl9WYdnBO5oQvnUa1mUsJRlI/lcdV6qYkRtbXqXF8LW/3P9Z12668KpO82NQUFDUV0lAncSVcJQiZuoCOgPnDExdrtyoq7uRegAW4tYEzEOmFXegT1NiIbmXB3gneDT2hL8v1
  template:
    metadata:
      creationTimestamp: null
      name: postgres-backup-minio-creds
      namespace: threads-dev
