apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: threads-dev

resources:
  - 01-sealedsecret.yaml
  - 02-cluster.yaml
  - 03-backup-sealedsecret.yaml
  - 04-scheduled-backup.yaml
