apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-configmap.yaml
  - 02-statefulset.yaml
  - 03-service.yaml
  - 04-ilm-policies.yaml

commonLabels:
  component: elasticsearch
  part-of: elk-stack
