apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: threads-dev

resources:
  - ../../../base/filebeat

patches:
  - patch: |-
      - op: add
        path: /subjects/0/namespace
        value: threads-dev
    target:
      kind: ClusterRoleBinding
      name: filebeat
