apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: threads-dev
resources:
  - ../../../base/haohan

images:
  - name: dangnam141002/haohan
    newName: dangnam141002/haohan
    newTag: latest
