apiVersion: apps/v1
kind: Deployment
metadata:
  name: haohan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haohan
  template:
    metadata:
      labels:
        app: haohan
    spec:
      containers:
        - name: haohan
          image: dangnam141002/haohan:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: MINIO_ENDPOINT
              value: "minio-api.namth.online"
            - name: MINIO_USE_SSL
              value: "true"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: haohan-secrets
                  key: minio-access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: haohan-secrets
                  key: minio-secret-key
            - name: MINIO_BUCKET_NAME
              value: "haohan"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
